### ISSUE TITLE
Docker-compose explanation

### ISSUE THREAD

**Issue by jos149** [guillaumedsde/alpine-qbittorrent-openvpn#104]
## Information

Before starting my container with docker compose I want to know a few things. I am not a network expert so that's why I am asking you. I don't want to mess up my other services.

## Current setup

I am running a raspberry pi server in my network with several services. As a gateway I have a DDWRT flashed router with a external HDD connected. This HDD is shared over samba. I have set the path of this drive in my docker-compose file. I am **not** running NordVPN on my router.

## `docker-compose.yml` file or `docker run` command
I copied the docker-compose file and adjusted a few things. My question is: what do I have to fill in `LAN`? My gateway 192.168.1.1? Or what does it mean??? And; will this docker container only be connected over vpn on its own? Or will my other containers also be tunneled over VPN? Because this I want to avoid. Maybe you have other suggestions for me? I just want a torrenting service to download data to my hdd at my samba share. Thanks in advance. Underneath you can find my docker compose file.

```yaml
version: "3.3"
services:
  alpine-qbittorrent-openvpn:
    volumes:
      - "/your/storage/path/:/downloads"
      - "/path/to/config/directory:/config"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - OPENVPN_PROVIDER=NORDVPN
      - NORDVPN_COUNTRY=NL
      - OPENVPN_USERNAME=emailnordvpn
      - OPENVPN_PASSWORD=pass
      - PUID=1000
      - PGID=1000
      - LAN=192.168.0.0/16 <--my gateway LAN????
    ports:
      - "8888:8080"
    cap_add:
      - NET_ADMIN
    image: guillaumedsde/alpine-qbittorrent-openvpn:latest
```

**Comment by jos149** [comment]
Anyone?

**Comment by MoistHoagie** [comment]
My understanding is this is the CIDR block for your local network.  So like mine is 192.168.1.0/24 which is super common.  You should be able to find this in your router or running something like ipconfig /all on Windows.  Find your network device, and then check the subnet mask.  Most likely it's 255.255.255.0 which is /24.

**Comment by jos149** [comment]
> My understanding is this is the CIDR block for your local network. So like mine is 192.168.1.0/24 which is super common. You should be able to find this in your router or running something like ipconfig /all on Windows. Find your network device, and then check the subnet mask. Most likely it's 255.255.255.0 which is /24.

Cool thanks! Explains a lot.

And do you also happen to know anything about the VPN settings and which traffic is tunneled over VPN?

**Comment by MoistHoagie** [comment]
Docker containers each have their own network so they should all go over your open internet, unless you specify a VPN connection for the container.  If you have access into the container directly (I use Portainer and I can get into it easily), you can run something like _curl ifconfig.io_ and it will return the IP so you can double verify.

**Comment by jos149** [comment]
> Docker containers each have their own network so they should all go over your open internet, unless you specify a VPN connection for the container. If you have access into the container directly (I use Portainer and I can get into it easily), you can run something like _curl ifconfig.io_ and it will return the IP so you can double verify.

I run portainer too, so yes, I can verify. The thing is; with the configuration of my docker containers as displayed above I want to know if I am connecting my whole server or only that container over VPN.

**Comment by MoistHoagie** [comment]
My understanding is it would just be that container over VPN.  If you run that command in a different container to check take note of the IP.  If it matches your public IP (You can check that by just typing _What is my ip_ into Google, then it isn't going over VPN.  If it doesn't match, then that public IP is from your VPN provider and that container is going over VPN.  Hope that helps.

**Comment by jos149** [comment]
Cool thanks.

I tried running docker-compose with the configuration as showed above. Sadly, I get `stopped with exit code 0`.
Portainer shows me the following log:
```
s6-svscan: warning: unable to iopause: Operation not permitted
s6-svscan: warning: executing into .s6-svscan/crash
s6-supervise s6-fdholderd: fatal: unable to iopause: Operation not permitted
s6-svscan panicked! Dropping to a root shell.
```

Anyone?

**Comment by ankorite** [comment]
So did you run it with this:
`volumes:
      - "/your/storage/path/:/downloads"
      - "/path/to/config/directory:/config"
      - "/etc/localtime:/etc/localtime:ro"`

Where is says "/your/storage/path/" it will need to be changed to your storage path on your host. Same with the config.

I am guessing /path/to/config/directory does not exist on your host system.

**Comment by jos149** [comment]
> I am guessing /path/to/config/directory does not exist on your host system.

I have a samba mount as a path to the storage.

My config folder exists but it does not contain anything. What should be in there?

**Comment by ankorite** [comment]
Ok, lets do these one at a time. 

You are supposed to change the "/path/to/config/directory" part in the compose file to your actual config directory where the docker user has permissions to read and write. I thought you where using Portainer correct? If so you can use its volume manager to deal with the config dir.

Change this:
`- "/path/to/config/directory:/config"`
To this:
`- qbittorrent-config:/config`

What VPN provider are you paying for? That is going to dictate the VPN settings you will need to use. Do you have a subscription with NordVPN?

On the host system what is your storage path? "/your/storage/path" is a placeholder and you need to change it to your actual path where you are storing your downloads i.e. "/home/pi/downloads"

If you do not have an account with a supported VPN this container will not work as far as I know.

**Comment by jos149** [comment]
> You are supposed to change the "/path/to/config/directory" part in the compose file to your actual config directory where the docker user has permissions to read and write. I thought you where using Portainer correct? If so you can use its volume manager to deal with the config dir.

Yes I do use Portainer. But to clarify; I have my docker compose file placed in `home/pi/torrent` where the docker user has permissions.

> Change this: `- "/path/to/config/directory:/config"` To this: `- qbittorrent-config:/config`

Done, already did it first time. My folder is named `config` instead of `qbittorrent-config`, is it a problem?

> What VPN provider are you paying for? That is going to dictate the VPN settings you will need to use. Do you have a subscription with NordVPN?

Yes I have a paid subscription for NordVPN. So wondering what settings do apply. Is it also required to download these config files from their website?

> On the host system what is your storage path? "/your/storage/path" is a placeholder and you need to change it to your actual path where you are storing your downloads i.e. "/home/pi/downloads"

I have a folder within the `torrent` folder which I mentioned before which is called `NAS` and this folder has the hard drive mounted over samba. I tested it functionality by placing a file from my laptop and checking whether it appears on my pi, it does!

Here you can find my current settings:
```
version: "3.3"
services:
  alpine-qbittorrent-openvpn:
    volumes:
      - "./NAS:/downloads"
      - "./config:/config"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_CONFIG=NL
      - OPENVPN_USERNAME=user
      - OPENVPN_PASSWORD=pass
      - PUID=1000
      - PGID=1000
      - LAN=192.168.1.1/24
    ports:
      - "8888:8080"
    cap_add:
      - NET_ADMIN
    image: guillaumedsde/alpine-qbittorrent-openvpn:latest
    container_name: torrentserver
    restart: always
```

As you know, config is now still empty.

Hope you can help me out. Thanks in advance!
