### ISSUE TITLE
Mullvad doesn't work without IPv6 support

### ISSUE THREAD

**Issue by BasixKOR** [guillaumedsde/alpine-qbittorrent-openvpn#111]
## Information
Mullvad doesn't work without IPv6 support. The exact error phrase might be a little different depending on the environment, but mine was:

```
2022-01-06 21:38:01 /usr/sbin/ip-su -6 addr add fdda:d0d0:cafe:1300::1002/64 dev tun1
RTNETLINK answers: Permission denied
2022-01-06 21:38:01 Linux ip -6 addr add failed: external program exited with error status: 22022-01-06 21:38:01 Exiting due to fatal error
```

## Current setup

_information about your current setup_

| docker image tag (ex: `python`, `latest`, `32242d1` ...) |  latest   |
| -------------------------------------------------------- | --- |
| docker image hash (ex: `603b78e07727`)                   |     |

## `docker-compose.yml` file or `docker run` command

_how did you start the container?_ (don't forget to use backticks for creating a proper code block)

```yaml
# I deployed it using Synology wizard. This is written to be as close to my setup as possible.
version: "3.3"
services:
  alpine-qbittorrent-openvpn:
    volumes:
      - "/volume1/video/torrents:/downloads"
      - "/volume1/docker/qbittorrent-config:/config"
    environment:
      - OPENVPN_PROVIDER=MULLVAD
      - OPENVPN_CONFIG=jp_all
      - OPENVPN_USERNAME=secret
      - OPENVPN_PASSWORD=m
      - LAN=192.168.50.0/24
    ports:
      - "9092:8080"
    cap_add:
      - NET_ADMIN
    image: guillaumedsde/alpine-qbittorrent-openvpn:latest
```

## Attempted Fix(es)

_What you have tried in order to fix the issue_ (if anything)

Appending `--pull-filter ignore ifconfig-ipv6` to OpenVPN option worked on docker-transmission-openvpn but after looking at source code I noticed there's no equivalent for `OPENVPN_OPTS` environment variable. This should be better discussed in a separate issue: #112.

## Related issues
* https://github.com/haugene/docker-transmission-openvpn/issues/1355
