### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by macieqq** [guillaumedsde/alpine-qbittorrent-openvpn#115]
## Information

Container does not start up:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-setup-permissions: executing... 
[cont-init.d] 01-setup-permissions: exited 0.
[cont-init.d] 02-setup-openvpn: executing... 
2022-01-19 22:52:38 TUN/TAP device tun0 opened
2022-01-19 22:52:38 Persist state set to: ON
INFO: Trying to use OpenVPN provider: NORDVPN

A    nordvpn
A    nordvpn/configure-openvpn.sh
Exported revision 1276.
Provider NORDVPN has a custom startup script, executing it
/var/run/s6/etc/cont-init.d/02-setup-openvpn: /etc/openvpn/nordvpn/configure-openvpn.sh: line 89: syntax error: unexpected "(" (expecting "}")
[cont-init.d] 02-setup-openvpn: exited 2.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

## Current setup

`guillaumedsde/alpine-qbittorrent-openvpn:latest`

## `docker-compose.yml` file or `docker run` command

```
version: "3.3"
services:
  alpine-qbittorrent-openvpn:
    volumes:
      - "/volume1/Data/Downloads:/downloads"
      - "/volume1/docker/qbittorrent-openvpn/config:/config"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_USERNAME=myusername
      - OPENVPN_PASSWORD=mypassword
      - PUID=1026
      - PGID=100
      - LAN=192.168.0.0/16
    ports:
      - "8080:8080"
    cap_add:
      - NET_ADMIN
    image: guillaumedsde/alpine-qbittorrent-openvpn:latest
```
