### ISSUE TITLE
unauthorized via proxy

### ISSUE THREAD

**Issue by procheeseburger** [guillaumedsde/alpine-qbittorrent-openvpn#120]
## Information

I have the container working just fine via compose but I can only access the webUI via  ip:8080 I can't seem to get it to work behind my proxy: qbit.domain.com. I get a white screen that says unauthorized. 

## Current setup

All of my containers run behind NGINX Proxy Manager and it works just fine. This one just seems to respond with unauthorized. 

_how did you start the container?_ (don't forget to use backticks for creating a proper code block)

```yaml
version: "3.9"
services:
  alpine-qbittorrent-openvpn:
    container_name: qbit
    image: guillaumedsde/alpine-qbittorrent-openvpn
    networks:
      - proxy
    volumes:
      - "${FILE1}:/downloads"
      - "qbit2:/config"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - OPENVPN_CONFIG=${OPENVPN_CONFIG}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - LAN=192.168.0.0/16
      - TUN=/dev/net/tun
      - DNS=${DNS}
      - HEALTH_CHECK_HOST=google.com
    ports:
      - "8080:8080"
    cap_add:
      - NET_ADMIN

volumes:
  qbit2:
    external: true

networks:
  proxy:
    external: true
```

## Attempted Fix(es)

There are similar issues, I've tried adjusted the qBittorrent.conf to match without success.
