### ISSUE TITLE
IP is leaking through 

### ISSUE THREAD

**Issue by Alfagun74** [guillaumedsde/alpine-qbittorrent-openvpn#137]
## Information
I just checked the IPs my Torrent Setup is leaking to the outside and was shocked finding out that my VPN IP **AND** my real IP are leaking through. I used this Tool: (ipleak.net)

![Unbenannt](https://user-images.githubusercontent.com/22225051/194045211-d2a080e8-c439-4c2f-aeaa-a9308a887b65.png)

## Current setup

_information about your current setup_

| docker image tag (ex: `python`, `latest`, `32242d1` ...) |   python  |
| -------------------------------------------------------- | --- |
| docker image hash (ex: `603b78e07727`)                   |   f696e56e6591  |

## `docker-compose.yml` file or `docker run` command

_how did you start the container?_ (don't forget to use backticks for creating a proper code block)

```yaml
version: "3.3"
services:
  alpine-qbittorrent-openvpn:
    environment:
      - OPENVPN_PROVIDER=SURFSHARK
      - OPENVPN_CONFIG=la-vte.prod.surfshark.com_udp
      - OPENVPN_USERNAME=REDACTED
      - OPENVPN_PASSWORD=REDACTED
      - PUID=1000
      - PGID=1000
      - LAN=0.0.0.0/0
    ports:
      - "8080:8080"
    cap_add:
      - NET_ADMIN
    image: guillaumedsde/alpine-qbittorrent-openvpn:latest
```
