### ISSUE TITLE
svn: E170013: Unable to connect to a repository at URL 'https://github.com/haugene/vpn-configs-contrib.git/trunk/openvpn/expressvpn'

### ISSUE THREAD

**Issue by GNUGradyn** [guillaumedsde/alpine-qbittorrent-openvpn#138]
## Information

Unable to use expressVPN due to error pulling from haugene/vpns-configs-contrib via svn

## Current setup

_information about your current setup_

| docker image tag (ex: `python`, `latest`, `32242d1` ...) |  latest   |
| -------------------------------------------------------- | --- |
| docker image hash (ex: `603b78e07727`)                   |   54fdfe50324c  |

## `docker-compose.yml` file or `docker run` command
_how did you start the container?_ (don't forget to use backticks for creating a proper code block)

```yaml
version: "3.3"
services:
  alpine-qbittorrent-openvpn:
    volumes:
      - "/mnt/plex/Downloads/:/mnt/plex/Downloads"
      - type: bind
        source: /home/gradyn/qbit/config.ovpn
        target: /config/openvpn/config.ovpn
      - "/etc/localtime:/etc/localtime:ro"
      - "/home/gradyn/qbit/config:/config"
    environment:
      - OPENVPN_PROVIDER=EXPRESSVPN
      - OPENVPN_CONFIG=my_expressvpn_usa_-_salt_lake_city_udp
      - OPENVPN_USERNAME=[SNIP]
      - OPENVPN_PASSWORD=[SNIP]
      - PUID=1000
      - PGID=1000
      - LAN=192.168.1.0/24
    ports:
      - "8080:8080"
    cap_add:
      - NET_ADMIN
    image: guillaumedsde/alpine-qbittorrent-openvpn:latest
```

## Attempted Fix(es)

_What you have tried in order to fix the issue_ (if anything)
Made sure host machine is able to pull that repo
