### ISSUE TITLE
Network Speed  slow <=10MB/s

### ISSUE THREAD

**Issue by G5K-org** [guillaumedsde/alpine-qbittorrent-openvpn#140]
## Information

Download speeds <10 MBytes with qBit and Openvpn on various well seeded torrent files.

# Current setup
OMV + OMV extras + Docker + mergefs on Server 
1Gb Ethernet lan
1Gbit ISP

| docker image tag (ex: `python`, `latest`, `32242d1` ...) |     |
| -------------------------------------------------------- | --- |
| docker image hash (ex: `603b78e07727`)                   |     |

## `docker-compose.yml` file or `docker run` command

```yaml
version: "3.3"
services:
  alpine-qbittorrent-openvpn:
    restart: unless-stopped
    volumes:
      - "/srv/mergerfs/Merge_FS/Torrents:/downloads"
      - "/home/docker/openvpn-qbit/config/directory:/config"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - OPENVPN_PROVIDER=PROTONVPN
      - OPENVPN_CONFIG=se.protonvpn.net.tcp
      - OPENVPN_USERNAME=XXX
      - OPENVPN_PASSWORD=XXX
      - PUID=998
      - PGID=100
      - LAN=192.168.0.0/16
    ports:
      - "8080:8080"
    cap_add:
      - NET_ADMIN
    image: guillaumedsde/alpine-qbittorrent-openvpn:latest

```

## Attempted Fix(es)
- tried different vpn-server
- no config issue in qBit so far as i know
_What you have tried in order to fix the issue_ (if anything)
- worked with transmission-Openvpn i got 90+MBytes
- worked with qBit+VPN on a standalone Machine and without Docker
