### ISSUE TITLE
Access from devices on local network?

### ISSUE THREAD

**Issue by CoreyVidal** [guillaumedsde/alpine-qbittorrent-openvpn#16]
## Information

I'm wondering if there's customization for the firewall settings so I can access qBittorrent over my local network, including other devices on the network. I'm trying to control qBittorrent via the Android app [nzb360](https://play.google.com/store/apps/details?id=com.kevinforeman.nzb360) (it's an awesome app).

## Current setup

guillaumedsde/alpine-qbittorrent-openvpn:latest running on Docker. Using docker-compose.
Traefik 2.0 providing a reverse proxy so I can serve my docker containers to my web server, get certificates, use Google OAuth, etc.
Basically my setup follows [this docker/server guide](https://www.smarthomebeginner.com/traefik-2-docker-tutorial/) fairly closely, except I swapped out transmission-openvpn for yours. :)
Because of Traefik, I can't access qbittorrent-openvpn on localhost:port. I have to access it at custom.local.ip.address:port.

## `docker-compose.yml` file or `docker run` command

docker-compose

(Note: I serve my OpenVPN config from a separate file.)

```yaml
version: "3.7"
services:
  qbittorrent-openvpn:
    container_name: qbittorrent-openvpn
    image: guillaumedsde/alpine-qbittorrent-openvpn:latest
    cap_add:
      - NET_ADMIN
    restart: always
    networks:
      t2_proxy:
        ipv4_address: $QBITTORRENT_IP
    ports:
      - "$QBITTORRENT_PORT:8080"
    volumes:
      - "REDACTED:/config"
      - "REDACTED:/Storage"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      OPENVPN_PROVIDER:     (this is left blank)
      OPENVPN_CONFIG:     (this is left blank)
      OPENVPN_USERNAME: REDACTED
      OPENVPN_PASSWORD: REDACTED
      PUID: $PUID
      PGID: $PGID
      LAN: $LOCAL_NETWORK
      HEALTH_CHECK_HOST: bing.com
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.qbittorrent-rtr.entrypoints=https"
      - "traefik.http.routers.qbittorrent-rtr.rule=HostHeader(`qbittorrent.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.qbittorrent-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.qbittorrent-rtr.service=qbittorrent-svc"
      - "traefik.http.services.qbittorrent-svc.loadbalancer.server.port=8080"
```

## Attempted Fix(es)

Banging it. Yelling at it. Threatening it.
Researched docker-transmission-openvpn. I think they have some firewall settings, like:
ENABLE_UFW
UFW_ALLOW_GW_NET
UFW_EXTRA_PORTS

Wondering if you had any thoughts/ideas/suggestions.
