### ISSUE TITLE
Health Check is pinging every 10 seconds

### ISSUE THREAD

**Issue by CoreyVidal** [guillaumedsde/alpine-qbittorrent-openvpn#18]
## Information

I have a Pihole and it shows me what's getting requested on my network. alpine-qbittorrent-openvpn is pinging an external address as a health check over 10,000 times a day.

## Current setup

guillaumedsde/alpine-qbittorrent-openvpn:latest
Running in the latest Docker via docker-compose, running on Ubuntu 20.04.

## `docker-compose.yml` file or `docker run` command

```yaml
version: "3.8"
services:
  alpine-qbittorrent-openvpn:
    volumes:
      - "/my/storage/path/:/downloads"
      - "/path/to/config/directory:/config"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      OPENVPN_PROVIDER:
      OPENVPN_CONFIG:
      OPENVPN_USERNAME: $VPN_USERNAME
      OPENVPN_PASSWORD: $VPN_PASSWORD
      PUID: $PUID
      PGID: $PGID
      DNS: $DNS
      LAN: 192.168.1.0/24 # $LOCAL_NETWORK
      HEALTH_CHECK_HOST: bing.com
      TZ: $TZ
    ports:
      - "8080:8080"
    cap_add:
      - NET_ADMIN
    restart: always
    image: guillaumedsde/alpine-qbittorrent-openvpn:latest
```

## Attempted Fix(es)

I stopped the container. It stopped pinging.
