### ISSUE TITLE
Not able to start torrent file; stuck in "downloading metadata"

### ISSUE THREAD

**Issue by rshamsz** [guillaumedsde/alpine-qbittorrent-openvpn#19]
## Information

torrent file stuck in "Downloading Metadata" state.
## Current setup

_information about your current setup_

guillaumedsde/alpine-qbittorrent-openvpn:latest@sha256:2ae14174f55be6a17a7128f2d0352d3b05239a00eaf26b4801691d7b213becda

## `docker-compose.yml` file or `docker run` command

_how did you start the container?_ (don't forget to use backticks for creating a proper code block)

```yaml
  qbittorrentvpn:
    image: guillaumedsde/alpine-qbittorrent-openvpn:latest
    container_name: qbittorrentvpn
    hostname: qbittorrentvpn_MS2
    restart: always
    networks:
      t2_proxy:
        ipv4_address: ${QBITTORRENTVPN_IP_INTERNAL} # You can specify a static IP,192.168.90.230
    cap_add:
      - NET_ADMIN
    ports:
      - "$QBITTORRENTVPN_SEED_PORT:6881"
      - "$QBITTORRENTVPN_SEED_PORT:6881/udp"
      - "$QBITTORRENTVPN_GUI_PORT:8080"
    privileged: true
    environment:
      OPENVPN_USERNAME: $EXPRESSVPN_USERNAME
      OPENVPN_PASSWORD: $EXPRESSVPN_PASSWORD
      OPENVPN_PROVIDER: $VPN_PROVIDER
      OPENVPN_CONFIG: $VPN_SERVER
      LAN_NETWORK: $LOCAL_NETWORK
      NAME_SERVERS: 1.0.0.1,209.222.18.222,84.200.69.80,37.235.1.174,1.1.1.1,209.222.18.218,37.235.1.177,84.200.70.40
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      UMASK_SET: 002
    volumes:
      - $USERDIR/QBittorrentVPN/config:/config
      - $GDRIVE_1/downloads/complete:/downloads/complete
      - $GDRIVE_1/downloads/incomplete:/downloads/incomplete
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "docker.group=MS2-Download"
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.qbittorrent-vpn-rtr.entrypoints=https"
      - "traefik.http.routers.qbittorrent-vpn-rtr.rule=Host(`qbit.$DOMAINNAME`)"
      - "traefik.http.routers.qbittorrent-vpn-rtr.tls=true"
```

## Attempted Fix(es)

There is nothing in the log; VPN connection is established and got an Ip form the VPN provider; 
Ports are assigned correctly:

Port configuration | 
0.0.0.0:6881  6881/tcp
0.0.0.0:6881  6881/udp
0.0.0.0:42525  8080/tcp

-- | --
I do not know if EXpressVPN support port forwarding or I need to enable it here
------

```
Mon Aug 24 20:04:09 2020 WARNING: --keysize is DEPRECATED and will be removed in OpenVPN 2.6

Mon Aug 24 20:04:09 2020 OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020

Mon Aug 24 20:04:09 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10

Mon Aug 24 20:04:09 2020 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.

Mon Aug 24 20:04:09 2020 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication

Mon Aug 24 20:04:09 2020 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication

Mon Aug 24 20:04:09 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]*.*.81.173:1195

Mon Aug 24 20:04:09 2020 Socket Buffers: R=[212992->425984] S=[212992->425984]

Mon Aug 24 20:04:09 2020 UDP link local: (not bound)

Mon Aug 24 20:04:09 2020 UDP link remote: [AF_INET]*.*.81.173:1195

Mon Aug 24 20:04:09 2020 TLS: Initial packet from [AF_INET]*.*.81.173:1195, sid=*****454 33ee6019

Mon Aug 24 20:04:09 2020 VERIFY OK: depth=1, C=VG, ST=BVI, O=ExpressVPN, OU=ExpressVPN, CN=ExpressVPN CA, emailAddress=support@expressvpn.com

Mon Aug 24 20:04:09 2020 VERIFY OK: nsCertType=SERVER

Mon Aug 24 20:04:09 2020 VERIFY X509NAME OK: C=VG, ST=BVI, O=ExpressVPN, OU=ExpressVPN, CN=Server-4312-0a, emailAddress=support@expressvpn.com

Mon Aug 24 20:04:09 2020 VERIFY OK: depth=0, C=VG, ST=BVI, O=ExpressVPN, OU=ExpressVPN, CN=Server-4312-0a, emailAddress=support@expressvpn.com

Mon Aug 24 20:04:09 2020 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 2048 bit RSA

Mon Aug 24 20:04:09 2020 [Server-4312-0a] Peer Connection Initiated with [AF_INET]*.*.81.173:1195

Mon Aug 24 20:04:10 2020 SENT CONTROL [Server-4312-0a]: 'PUSH_REQUEST' (status=1)

Mon Aug 24 20:04:10 2020 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 10.72.0.1,comp-lzo no,route 10.72.0.1,topology net30,ping 10,ping-restart 60,ifconfig 10.72.0.94 10.72.0.93,peer-id 24,cipher AES-256-GCM'

Mon Aug 24 20:04:10 2020 Pushed option removed by filter: 'dhcp-option DNS 10.72.0.1'

Mon Aug 24 20:04:10 2020 OPTIONS IMPORT: timers and/or timeouts modified

Mon Aug 24 20:04:10 2020 OPTIONS IMPORT: compression parms modified

Mon Aug 24 20:04:10 2020 OPTIONS IMPORT: --ifconfig/up options modified

Mon Aug 24 20:04:10 2020 OPTIONS IMPORT: route options modified

Mon Aug 24 20:04:10 2020 OPTIONS IMPORT: peer-id set

Mon Aug 24 20:04:10 2020 OPTIONS IMPORT: adjusting link_mtu to 1629

Mon Aug 24 20:04:10 2020 OPTIONS IMPORT: data channel crypto options modified

Mon Aug 24 20:04:10 2020 Data Channel: using negotiated cipher 'AES-256-GCM'

Mon Aug 24 20:04:10 2020 NCP: overriding user-set keysize with default

Mon Aug 24 20:04:10 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key

Mon Aug 24 20:04:10 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key

Mon Aug 24 20:04:10 2020 ROUTE_GATEWAY 192.168.90.1/255.255.255.0 IFACE=eth0 HWADDR=*:*:c0:a8:5a:*

Mon Aug 24 20:04:10 2020 TUN/TAP device tun1 opened

Mon Aug 24 20:04:10 2020 TUN/TAP TX queue length set to 100

Mon Aug 24 20:04:10 2020 /usr/sbin/ip-su link set dev tun1 up mtu 1500

Mon Aug 24 20:04:10 2020 /usr/sbin/ip-su addr add dev tun1 local 10.72.0.94 peer 10.72.0.93

INFO: no port updater for provider EXPRESSVPN

******** Information ********

To control qBittorrent, access the Web UI at http://localhost:8080

Mon Aug 24 20:04:12 2020 /usr/sbin/ip-su route add *.*.81.173/32 via 192.168.90.1

Mon Aug 24 20:04:12 2020 /usr/sbin/ip-su route add 0.0.0.0/1 via 10.72.0.93

Mon Aug 24 20:04:12 2020 /usr/sbin/ip-su route add 128.0.0.0/1 via 10.72.0.93

Mon Aug 24 20:04:12 2020 /usr/sbin/ip-su route add 192.168.0.0/24 via 192.168.90.1

Mon Aug 24 20:04:12 2020 /usr/sbin/ip-su route add 10.72.0.1/32 via 10.72.0.93

Mon Aug 24 20:04:12 2020 Initialization Sequence Completed


````
![image](https://user-images.githubusercontent.com/44298524/91095246-0c717b00-e62a-11ea-8106-1df6ec975349.png)
![image](https://user-images.githubusercontent.com/44298524/91095292-1d21f100-e62a-11ea-8348-21a7a42bae38.png)
