### ISSUE TITLE
Nordvpn not about to find best config file.

### ISSUE THREAD

**Issue by NotChristianGarcia** [guillaumedsde/alpine-qbittorrent-openvpn#24]
## Information

Hey! Can't get NordVPN setup with the Alpine image. From the logs it looks like the NordVPN update script used in [haugenetransmission-openvpn](http://haugene.github.io/docker-transmission-openvpn/nordvpn-script/) isn't being called so Nord's required "NORD_COUNTRY" environment variable isn't being used and the "best config" file isn't be fetched. 

## Current setup

```
alpine-qbittorrent-openvpn_1  | [cont-init.d] 01-setup-permissions: executing...
alpine-qbittorrent-openvpn_1  | [cont-init.d] 01-setup-permissions: exited 0.
alpine-qbittorrent-openvpn_1  | [cont-init.d] 02-setup-openvpn: executing...
alpine-qbittorrent-openvpn_1  | Thu Sep  3 22:11:36 2020 TUN/TAP device tun0 opened
alpine-qbittorrent-openvpn_1  | Thu Sep  3 22:11:36 2020 Persist state set to: ON
alpine-qbittorrent-openvpn_1  | INFO: Trying to use OpenVPN provider: NORDVPN
alpine-qbittorrent-openvpn_1  | A    nordvpn
alpine-qbittorrent-openvpn_1  | A    nordvpn/updateConfigs.sh
alpine-qbittorrent-openvpn_1  | Exported revision 2308.
alpine-qbittorrent-openvpn_1  | ERROR: Could not find OpenVPN configuration "" for provider NORDVPN
alpine-qbittorrent-openvpn_1  | [cont-init.d] 02-setup-openvpn: exited 1.
```

## `docker-compose.yml` file or `docker run` command

```
version: "3.3"
services:
  alpine-qbittorrent-openvpn:
    volumes:
      - "/your/storage/path/:/downloads"
      - "/path/to/config/directory:/config"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - OPENVPN_PROVIDER=NORDVPN
      - NORDVPN_COUNTRY=US
      - OPENVPN_USERNAME=user
      - OPENVPN_PASSWORD=pass
      - PUID=1000
      - PGID=1000
      - LAN=192.168.0.0/16
    ports:
      - "8080:8080"
    cap_add:
      - NET_ADMIN
    image: guillaumedsde/alpine-qbittorrent-openvpn:development

```
## Attempted Fix(es)

Tried lots of setup options with different configs of the Nord environment variables. Looked through the code, but the s6 bits (so basically all of it) don't make much sense to me on first glance. Looks like maybe this isn't yet implemented? As Nord doesn't use preconfigured config files that are then parsed locally. Your non-alpine image works fine.
