### ISSUE TITLE
NordVPN: updateConfigs.sh not found

### ISSUE THREAD

**Issue by JasperMC** [guillaumedsde/alpine-qbittorrent-openvpn#35]
## Information
Whenever I attempt to use NordVPN with this container I get the following error:

```
/var/run/s6/etc/cont-init.d/02-setup-openvpn: /etc/openvpn/nordvpn/configure-openvpn.sh: line 12: 
/etc/openvpn/nordvpn/updateConfigs.sh: not found

ERROR: Could not find OpenVPN configuration "" for provider NORDVPN
```

This occurs both with the suggested configuration as well as with the NordVPN specific env variables as mentioned here: https://haugene.github.io/docker-transmission-openvpn/nordvpn-script/

As the files for NordVPN are coming from docker-transmission-openvpn, I also tried that container with the same configuration. The problem does not appear there.

My suspicion is that the script is looking for the file in the wrong place. I think it's because of the "${VPN_PROVIDER_HOME} variable. Trying to confirm that.

## Current setup

Docker image tag: latest
Docker image hash: sha256:8157f288e27d2b642f0aefd72b6f86174185e6e4eb310063d2d4b85720199dd6

## `docker-compose.yml` file or `docker run` command

Started using docker-compose.yaml:

```yaml
version: "3.3"
services:
  alpine-qbittorrent-openvpn:
    volumes:
      - "/your/storage/path/:/downloads"
      - "/path/to/config/directory:/config"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_CONFIG=NL\
      - OPENVPN_USERNAME=user
      - OPENVPN_PASSWORD=pass
      - PUID=1000
      - PGID=1000
      - LAN=192.168.0.0/16
    ports:
      - "8080:8080"
    cap_add:
      - NET_ADMIN
    image: guillaumedsde/alpine-qbittorrent-openvpn:latest
```

## Attempted Fix(es)

1. Set "behavior if S2 fails" to 0 to prevent termination
2. Went into the container to verify whether updateConfigs.sh exists (it does)
3. Tried with NordVPN-specific env variables (did not work)
