### ISSUE TITLE
Can not get it to work with Mullvad VPN

### ISSUE THREAD

**Issue by skrynklarn** [guillaumedsde/alpine-qbittorrent-openvpn#38]
## Information

Can not get it to work with Mullvad VPN. It works fine with example haugene/docker-transmission-openvpn.

## Current setup

Running docker on Raspberry Pi 4.

## `docker-compose.yml` file or `docker run` command

Using Docker Compose

```yaml
qbit:
  image: guillaumedsde/alpine-qbittorrent-openvpn:latest
  container_name: qbit
  volumes:
    - "/home/pi/docker/qbittorrent/downloads:/downloads"
    - "/home/pi/docker/qbittorrent/config:/config"
    - "/etc/localtime:/etc/localtime:ro"
  environment:
    - OPENVPN_PROVIDER=MULLVAD
    - OPENVPN_CONFIG=se_all
    - OPENVPN_USERNAME=***  # Masked my real username
    - OPENVPN_PASSWORD=*** # Masked my real password
    - LAN=10.0.0.0/16
  ports:
    - '8080:8080'
  cap_add:
    - NET_ADMIN
```

## Attempted Fix(es)

Tried various settings, but same "error".

## Docker logs

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-setup-permissions: executing... 
[cont-init.d] 01-setup-permissions: exited 0.
[cont-init.d] 02-setup-openvpn: executing... 
Sun Nov 22 01:11:36 2020 TUN/TAP device tun0 opened
Sun Nov 22 01:11:36 2020 Persist state set to: ON
INFO: Trying to use OpenVPN provider: MULLVAD
A    mullvad
A    mullvad/ae_all.ovpn
A    mullvad/al_all.ovpn
A    mullvad/at_all.ovpn
A    mullvad/au_all.ovpn
A    mullvad/be_all.ovpn
A    mullvad/bg_all.ovpn
A    mullvad/br_all.ovpn
A    mullvad/ca.crt
A    mullvad/ca_all.ovpn
A    mullvad/ch_all.ovpn
A    mullvad/cz_all.ovpn
A    mullvad/de_all.ovpn
A    mullvad/default.ovpn
A    mullvad/dk_all.ovpn
A    mullvad/es_all.ovpn
A    mullvad/fi_all.ovpn
A    mullvad/fr_all.ovpn
A    mullvad/gb_all.ovpn
A    mullvad/gr_all.ovpn
A    mullvad/hk_all.ovpn
A    mullvad/hu_all.ovpn
A    mullvad/ie_all.ovpn
A    mullvad/il_all.ovpn
A    mullvad/it_all.ovpn
A    mullvad/jp_all.ovpn
A    mullvad/lu_all.ovpn
A    mullvad/lv_all.ovpn
A    mullvad/md_all.ovpn
A    mullvad/nl_all.ovpn
A    mullvad/no_all.ovpn
A    mullvad/nz_all.ovpn
A    mullvad/pl_all.ovpn
A    mullvad/ro_all.ovpn
A    mullvad/rs_all.ovpn
A    mullvad/se_all.ovpn
A    mullvad/sg_all.ovpn
A    mullvad/update-resolv-conf
A    mullvad/us_all.ovpn
Exported revision 2581.
INFO: Found OpenVPN configuration: "se_all" for provider "MULLVAD" using it
[cont-init.d] 02-setup-openvpn: exited 0.
[cont-init.d] 03-setup-iptables: executing... 
iptables v1.8.4 (legacy): Port "1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302" does not resolve to anything.

Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.4 (legacy): Port "1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302
1302" does not resolve to anything.

Try `iptables -h' or 'iptables --help' for more information.
[cont-init.d] 03-setup-iptables: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Sun Nov 22 01:11:39 2020 Note: option tun-ipv6 is ignored because modern operating systems do not need special IPv6 tun handling anymore.
Sun Nov 22 01:11:39 2020 OpenVPN 2.4.9 armv7-alpine-linux-musleabihf [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020
Sun Nov 22 01:11:39 2020 library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
Sun Nov 22 01:11:39 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]185.65.135.152:1302
Sun Nov 22 01:11:39 2020 Socket Buffers: R=[180224->360448] S=[180224->360448]
Sun Nov 22 01:11:39 2020 UDP link local: (not bound)
Sun Nov 22 01:11:39 2020 UDP link remote: [AF_INET]185.65.135.152:1302
Sun Nov 22 01:11:39 2020 write UDP: Operation not permitted (code=1)
Sun Nov 22 01:11:41 2020 write UDP: Operation not permitted (code=1)
Sun Nov 22 01:11:45 2020 write UDP: Operation not permitted (code=1)
Sun Nov 22 01:11:54 2020 write UDP: Operation not permitted (code=1)
```
