### ISSUE TITLE
[bug] Cannot add torrent from search

### ISSUE THREAD

**Issue by blmhemu** [guillaumedsde/alpine-qbittorrent-openvpn#47]
## Information
Using the python tagged image.
1. Sometime double clicking on the search result does not work.
2. When it works, clicking on download does not add it to the queue.

## Current setup

guillaumedsde/alpine-qbittorrent-openvpn:python

## `docker-compose.yml` file or `docker run` command
```
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress
  namespace: default
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      securityContext:
        supplementalGroups: [REDACTED] // For nfs share
      containers:
      - image: guillaumedsde/alpine-qbittorrent-openvpn:python
        name: wordpress
        env:
        - name: PUID
          value: "REDACTED"
        - name: PGID
          value: "REDACTED"
        - name: OPENVPN_PROVIDER
          value: "REDACTED"
        - name: OPENVPN_CONFIG
          value: "REDACTED"
        - name: OPENVPN_USERNAME
          value: "REDACTED"
        - name: OPENVPN_PASSWORD
          value: "REDACTED"
        ports:
        - containerPort: 8080
          name: qbt
        volumeMounts:
        - name: data
          mountPath: /config/qBittorrent
          subPath: qBittorrent
        - name: media
          mountPath: /downloads
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: nfs-data-pvc
      - name: media
        persistentVolumeClaim:
          claimName: nfs-media-pvc
```
## Attempted Fix(es)

Nothing
