### ISSUE TITLE
Gettings lots of Operation not permitted (code=1)

### ISSUE THREAD

**Issue by Demon-tk** [guillaumedsde/alpine-qbittorrent-openvpn#56]
## Information

Unable to download p2p files in qBitTorrent, however, the application does start

## Current setup

Ubuntu Server running lts, using docker container to run 

## `docker-compose.yml` file or `docker run` command

_how did you start the container?_ (don't forget to use backticks for creating a proper code block)

```yaml
version: "3.3"
services:
  alpine-qbittorrent-openvpn:
    volumes:
      - /media/data:/data
      - /home/nate/docker/qbit2/config:/config
      - /media/data/movies/airvpn.ovpn:/config/openvpn/config.ovpn
      #- "/etc/localtime:/etc/localtime:ro"
    environment:
      - OPENVPN_PROVIDER=
      #- OPENVPN_CONFIG=ca_toronto
      - OPENVPN_USERNAME=user
      - OPENVPN_PASSWORD=pass
      - PUID=1000
      - PGID=1000
      - LAN=10.0.0.1/24
    ports:
      - "8080:8080"
    cap_add:
      - NET_ADMIN
    image: guillaumedsde/alpine-qbittorrent-openvpn:latest
```

## Attempted Fix(es)

1. Restarting container
2. Rework config (guid and puid)
3. Using airVPN which may pose some issues, I followed the information on the wiki to properly configure it via the opvn config

## Log file
https://gist.github.com/Demon-tk/8bf9dcf1770d7c75c8fc21c555101d91
