### ISSUE TITLE
write UDP: Operation not permitted (code=1) using ExpressVPN

### ISSUE THREAD

**Issue by Leiasticot** [guillaumedsde/alpine-qbittorrent-openvpn#59]
## Information

Here is what I got inside my portainer logs :

```
Mon Jan 11 22:40:40 2021 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.


Mon Jan 11 22:40:40 2021 TCP/UDP: Preserving recently used remote address: [AF_INET]84.17.43.194:1195


Mon Jan 11 22:40:40 2021 Socket Buffers: R=[180224->360448] S=[180224->360448]


Mon Jan 11 22:40:40 2021 UDP link local: (not bound)


Mon Jan 11 22:40:40 2021 UDP link remote: [AF_INET]84.17.43.194:1195


Mon Jan 11 22:40:40 2021 write UDP: Operation not permitted (code=1)


Mon Jan 11 22:40:42 2021 write UDP: Operation not permitted (code=1)


Mon Jan 11 22:40:46 2021 write UDP: Operation not permitted (code=1)


Mon Jan 11 22:40:54 2021 write UDP: Operation not permitted (code=1)


Mon Jan 11 22:41:10 2021 write UDP: Operation not permitted (code=1)


Mon Jan 11 22:41:40 2021 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)


Mon Jan 11 22:41:40 2021 TLS Error: TLS handshake failed


Mon Jan 11 22:41:40 2021 SIGUSR1[soft,tls-error] received, process restarting


Mon Jan 11 22:41:40 2021 Restart pause, 5 second(s)
```

## Current setup

I'm using a Raspberry pi 4 running on Raspberry pi OS.
I use a manual config.ovpn (I run a first time without and I got an error, then I move my config.ovpn inside /openvpn/config.ovpn
then I restart the container.

## `docker-compose.yml` file or `docker run` command

```yaml
version: "3.7"
services:
  alpine-qbittorrent-openvpn:
    container_name: qbittorrentvpn
    volumes:
      - /mnt/BLACKPEARL/seedbox:/downloads
      - ~/docker/qbittorrent:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - OPENVPN_USERNAME=expressvpnusername
      - OPENVPN_PASSWORD=expressvpnpassword
      - PUID=1000
      - PGID=1000
      - LAN=192.168.1.0/24
    ports:
      - "8080:8080"
    cap_add:
      - NET_ADMIN
    image: guillaumedsde/alpine-qbittorrent-openvpn:latest
```

Here is my config.ovpn

```
dev tun
fast-io
persist-key
persist-tun
nobind
remote france-paris-2-ca-version-2.expressnetw.com 1195
remote-random
pull
comp-lzo no
tls-client
verify-x509-name Server name-prefix
ns-cert-type server
key-direction 1
route-method exe
route-delay 2
tun-mtu 1500
fragment 1300
mssfix 1200
verb 3
cipher AES-256-CBC
keysize 256
auth SHA512
sndbuf 524288
rcvbuf 524288
auth-user-pass

CERTIFICATE
```

## Attempted Fix(es)

Tried to change the server inside the config.ovpn
Tried to use NordVPN (but I can't make it work)

**Comment by vadimstasiev** [comment]
Have the same bug using HMA (HideMyAss)

**Comment by vadimstasiev** [comment]
I have the same issue with HMA (HideMyAss)
Here is the command that I run:

```
sudo docker run --restart unless-stopped --cap-add=NET_ADMIN -d \
              -v /etc/docker-configs/qBittorrent:/config/qBittorrent/data/BT_backup \
              -v /etc/docker-configs/qBittorrent/GeoDB:/config/qBittorrent/data/GeoDB \
              -v /etc/docker-configs/qBittorrent/rss:/config/qBittorrent/data/rss \
              -v /etc/docker-configs/qBittorrent/config:/config/qBittorrent/config \
              -v /etc/docker-configs/qBittorrent/cache:/config/qBittorrent/cache \
              -v /home/server/Media/library/torrent:/data \
              -e OPENVPN_PROVIDER=HIDEMYASS \
              -e OPENVPN_USERNAME=user \
              -e OPENVPN_PASSWORD=pass \
	      -e PUID=1000 \
              -e PGID=1000 \
              -e LAN=192.168.0.0/24 \
              -p 8080:8080 \
              guillaumedsde/alpine-qbittorrent-openvpn:latest
```

**Comment by chrispalka** [comment]
Having same issue, this is literally the only container for ARM that I could get semi working with ExpressVPN. In a prior post, it was recommended to only have one remote in your config.ovpn file which I double checked.

**Comment by inertia666** [comment]
Using PrivateVPN and get a similar error but also an IPtables error.

Using a Raspberry PI 4 with OpenMediaVault and Docker/Iptables NFT.

>>iptables v1.8.4 (legacy): unknown protocol "'udp'" specified
>>write UDP: Operation not permitted (code=1)

I have the Tranmission container that this is based on and that works perfectly fine.

**Comment by inertia666** [comment]
> 
> 
> Having same issue, this is literally the only container for ARM that I could get semi working with ExpressVPN. In a prior post, it was recommended to only have one remote in your config.ovpn file which I double checked, but still running into this issue.

If you need something working for now then you should consider using the Transmission container

https://haugene.github.io/docker-transmission-openvpn/building-blocks/

It will get you up and running with something until these issues with QBT are fixed.

**Comment by chrispalka** [comment]
Thank you, I was not looking to do so, but may be worth the switch for now.

**Comment by Fischy667** [comment]
I'm using https://hub.docker.com/r/binhex/arch-qbittorrentvpn until this is fixed.

**Comment by LuisPerez64** [comment]
Issue comes up in the setup of the IP Tables. It's due to the way the VPN_PROTO env variable is defined. The multiple wrap arrounds of the quotes causes it to expand incorrectly. Excerpts of running `/etc/cont-init.d/03-setup-iptables` with `set -x` below
```
+ VPN_PROTO=''"'"'udp'"'"
... redacted 1 line
+ DNS_SERVER=1.1.1.1
... redacted 1 line
+ '[' -z ''"'"'udp'"'" ]
+ '[' ''"'"'udp'"'" '=' tcp-client ]
... redacted N unaffected lines
+ iptables -A OUTPUT -j ACCEPT -d usa-newyork-ca-version-2.expressnetw.com -o eth+ -p ''"'"'udp'"'" -m ''"'"'udp'"'" --dport 1195
iptables v1.8.4 (legacy): unknown protocol "'udp'" specified
Try `iptables -h' or 'iptables --help' for more information.
+ iptables -A INPUT -j ACCEPT -s usa-newyork-ca-version-2.expressnetw.com -i eth+ -p ''"'"'udp'"'" -m ''"'"'udp'"'" --sport 1195
iptables v1.8.4 (legacy): unknown protocol "'udp'" specified
Try `iptables -h' or 'iptables --help' for more information.
```

**Comment by ishaanx** [comment]
I am facing the same issue with Surfshark. 
On latest docker image. 

Here is my config - 
```
# QBT
  qbt:
    image: guillaumedsde/alpine-qbittorrent-openvpn:latest
    container_name: qbt
    cap_add:
      - NET_ADMIN
    volumes:
      - $DCDATA/qbt/config:/config
      - $DCDATA/qbt/downloads:/downloads
      - /mnt/hdd1:/hdd1
      - /mnt/hdd2:/hdd2
    environment:
      - OPENVPN_PROVIDER=
      - OPENVPN_CONFIG=$DCDATA/qbt/config/openvpn/config.ovpn
      - OPENVPN_USERNAME=$VPN_USERNAME
      - OPENVPN_PASSWORD=$VPN_PASSWORD
      - PUID=$PUID
      - PGID=$PGID
      - LAN=192.168.0.1/16
      - VIRTUAL_HOST=$TORRENT_VHOST
    expose:
      - 8080
    devices:
      - /dev/net/tun
    restart: always

```



Here is the error - 

```
qbt                 | 2021-09-29 16:38:29 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
qbt                 | 2021-09-29 16:38:29 TCP/UDP: Preserving recently used remote address: [AF_INET]156.146.62.46:1194
qbt                 | 2021-09-29 16:38:29 Socket Buffers: R=[212992->212992] S=[212992->212992]
qbt                 | 2021-09-29 16:38:29 UDP link local: (not bound)
qbt                 | 2021-09-29 16:38:29 UDP link remote: [AF_INET]156.146.62.46:1194
qbt                 | 2021-09-29 16:38:29 write UDP: Operation not permitted (code=1)
qbt                 | 2021-09-29 16:38:31 write UDP: Operation not permitted (code=1)
qbt                 | 2021-09-29 16:38:35 write UDP: Operation not permitted (code=1)
```
