### ISSUE TITLE
iptables prevents mullvad VPN from working

### ISSUE THREAD

**Issue by waddlefluf** [guillaumedsde/alpine-qbittorrent-openvpn#65]
## Information

iptables seems to prevent connecting to/pinging/etc anything. In the qBittorrent web client, attempting to torrent anything just results in getting stuck on "Stalled". In the shell of the container I tried pinging multiple websites/IPs (google.com, 1.1.1.1, etc.) and got the following result:
 ```
 / # ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1): 56 data bytes

ping: sendto: Operation not permitted
```
After completely disabling iptables, this doesn't happen, and I'm able to torrent normally.

iptables output:
```
/ # iptables -S
-P INPUT DROP
-P FORWARD DROP
-P OUTPUT DROP
-A INPUT -i lo -j ACCEPT
-A INPUT -s 1.1.1.1/32 -p udp -m udp --sport 53 -m state --state ESTABLISHED -j ACCEPT
-A INPUT -s 1.1.1.1/32 -p tcp -m tcp --sport 53 -m state --state ESTABLISHED -j ACCEPT
-A INPUT -s 192.168.0.0/16 -i eth+ -j ACCEPT
-A INPUT -s 172.21.0.0/16 -i eth+ -j ACCEPT
-A INPUT -s 198.54.134.66/32 -i eth+ -p udp -m udp --sport 1195 -j ACCEPT
-A INPUT -s 198.54.134.34/32 -i eth+ -p udp -m udp --sport 1195 -j ACCEPT
-A INPUT -s 198.54.134.50/32 -i eth+ -p udp -m udp --sport 1195 -j ACCEPT
-A INPUT -i tun+ -j ACCEPT
-A OUTPUT -o lo -j ACCEPT
-A OUTPUT -d 1.1.1.1/32 -p udp -m udp --dport 53 -m state --state NEW,ESTABLISHED -j ACCEPT
-A OUTPUT -d 1.1.1.1/32 -p tcp -m tcp --dport 53 -m state --state NEW,ESTABLISHED -j ACCEPT
-A OUTPUT -d 192.168.0.0/16 -o eth+ -j ACCEPT
-A OUTPUT -d 172.21.0.0/16 -o eth+ -j ACCEPT
-A OUTPUT -d 198.54.134.66/32 -o eth+ -p udp -m udp --dport 1195 -j ACCEPT
-A OUTPUT -d 198.54.134.34/32 -o eth+ -p udp -m udp --dport 1195 -j ACCEPT
-A OUTPUT -d 198.54.134.50/32 -o eth+ -p udp -m udp --dport 1195 -j ACCEPT
-A OUTPUT -o tun+ -j ACCEPT
```

## Current setup

Using Raspbian on a Raspberry Pi 4B
Docker version: 20.10.5, build 55c4c88
docker-compose version: 1.21.0

| docker image tag | latest |
| -------------------------------------------------------- |------|
| docker image hash                   | 65b44cd270c9 |

## `docker-compose.yml` file

```yaml
version: "3.3"
services:
  alpine-qbittorrent-openvpn:
    volumes:
      - "/mnt/data/storage/torrent/downloads/:/downloads"
      - "/home/pi/.config/qbitorrent-openvpn:/config"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - OPENVPN_PROVIDER=MULLVAD
      - OPENVPN_CONFIG=us_sjc
      - OPENVPN_USERNAME=*****
      - OPENVPN_PASSWORD=***** 
      - PUID=1000
      - PGID=1000
      - LAN=192.168.0.0/16
    ports:
      - "8080:8080"
    cap_add:
      - NET_ADMIN
    image: guillaumedsde/alpine-qbittorrent-openvpn:latest

```

## Attempted Fixes
* Restarting container and redoing docker-compose
* Like mentioned earlier, removing iptables fixes it, but I'm not sure what else to do for a more permanent fix.
