### ISSUE TITLE
keysize deprecated - ipvanish

### ISSUE THREAD

**Issue by akrea** [guillaumedsde/alpine-qbittorrent-openvpn#68]
Hi first of all

THANK YOU FOR YOUR TERRIFIC WORK!!!!! MUCH APPRECIATED!
I have an issue with using IPVanish 

## Information

I'm using IPVanish (in the haugene transmission-vpn). In 
```
--keysize is DEPRECATED and will be removed in OpenVPN 2.6
Options error: --ca fails with 'ca.ipvanish.com.crt': No such file or directory (errno=2)
Options error: Please correct these errors.
```

## Current setup

| docker version | `19.03.8, build afacb8b7f0`  |
| -------------------------------------------------------- | --- |
| docker image tag | `latest`    |

## `docker-compose.yml`

```yaml
version: "3.5"
services:
  alpine-qbittorrent-openvpn:
        container_name: qbittorrent-vpn
        image: guillaumedsde/alpine-qbittorrent-openvpn:latest
        hostname: qbittorrent-vpn
        cap_add:
            - NET_ADMIN
        networks:
            - t2_proxy
        security_opt:
            - no-new-privileges:true
        # devices:
            # - /dev/net/tun
        restart: unless-stopped
        ports:
            - $QBITTORRENT_PORT:8080
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - $USERDIR/qbittorrent:/config
            - $USERDIR/Downloads:/downloads
        environment:
            OPENVPN_PROVIDER: IPVANISH
            OPENVPN_USERNAME: ${MYEMAIL}
            OPENVPN_PASSWORD: ${PW6}
            LAN: "$LOCAL_NETWORK"
            PUID: 48
            PGID: 100
            TZ: ${TZ}
```

## Attempted Fix(es)

- So far I only tried to change the openvpn config file. Same error on any valid config.
- Same IPVanish parameters work on haugenes/transmission-vpn flawlessly
