### ISSUE TITLE
TLS Error: TLS object -> incoming plaintext read error

### ISSUE THREAD

**Issue by WormChickenWizard** [guillaumedsde/alpine-qbittorrent-openvpn#79]
## Information

Went to remote into the qbittorrent webui and I noticed the container didn't have internet. Usually its because the VPN connection got hung up and rebooting it seems to remedy the issue. Today however after literally changing nothing when it lost connection, I rebooted the container and the qbittorrent client never booted up. I checked the docker logs and it seems that there is some sort of TLS error preventing the VPN from initializing.

## Current setup

_information about your current setup_

| docker image tag (ex: `python`, `latest`, `32242d1` ...) |   `latest`  |
| -------------------------------------------------------- | --- |
| docker image hash (ex: `603b78e07727`)                   |  `28b3f5d6c9ce `  |

## `docker-compose.yml` file or `docker run` command

_how did you start the container?_ (don't forget to use backticks for creating a proper code block)

```yaml
  # Install qbittorrent with built-in openvpn client
  alpine-qbittorrent-openvpn:
    container_name: qbittorrent
    image: guillaumedsde/alpine-qbittorrent-openvpn:latest
    restart: unless-stopped
    networks:
      group_default:
        ipv4_address: 172.18.0.4
    ports:
      - "8080:8080"
    cap_add:
      - NET_ADMIN
    volumes:
      - /home/docker/qbittorrent/downloads:/downloads
      - /home/docker/qbittorrent/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /mnt/gdrive:/mnt/gdrive/
    environment:
      - OPENVPN_PROVIDER=WINDSCRIBE
      - OPENVPN_CONFIG=HongKong-Phooey-udp
      - OPENVPN_USERNAME=secret
      - OPENVPN_PASSWORD=secret
      - PUID=1000
      - PGID=1000
      - LAN=192.168.1.0/24
    dns:
      - 10.255.255.1
      - 1.1.1.1
      - 1.0.0.1
```

## Attempted Fix(es)

I tried switching servers and removing the dns entry from the docker-compose file and the issue still persists.
