### ISSUE TITLE
 Latest `python` tagged image on Docker Hub will not start

### ISSUE THREAD

**Issue by johnbintz** [guillaumedsde/alpine-qbittorrent-openvpn#80]
## Information

Latest `python` tagged image on Docker Hub will not start:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[cont-finish.d] executing container finish scripts...
[s6-finish] waiting for services.
s6-svwait: fatal: unable to subscribe to events for /var/run/s6/services/s6-fdholderd: Operation not permitted
```

## Current setup

Docker image tag: `python`
`docker version`:

```
Server:
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.6
  Git commit:       4c52b90
  Built:            Fri Sep 13 09:45:43 2019
  OS/Arch:          linux/arm
  Experimental:     false
```

## `docker-compose.yml` file or `docker run` command

I use Ansible to configure the container:

```yaml
  docker_container:
    name: qbittorrent
    image: guillaumedsde/alpine-qbittorrent-openvpn:python
    pull: true
    capabilities:
      - ALL
    env:
      OPENVPN_PROVIDER: "CUSTOM"
      OPENVPN_USERNAME: "<username>"
      OPENVPN_PASSWORD: "<password>"
      PUID: "1000"
      PGID: "1000"
      LAN: "192.168.1.0/24"
      CREATE_TUN_DEVICE: "true"
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      - "/etc/qbittorrent/config:/config"
      - "/downloads:/config/qBittorrent/downloads"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/custom.ovpn:/etc/openvpn/custom/default.ovpn:ro"
    restart_policy: always
    state: started
```

## Attempted Fix(es)

The last hash that wasn't updated this morning, `dd4cd24`, works, but has no Python support so I can't use search.
