### ISSUE TITLE
Won't start with custom OpenVPN config

### ISSUE THREAD

**Issue by MisterX2000** [guillaumedsde/alpine-qbittorrent-openvpn#81]
## Information

When I try to start the container with the OpenVPN config placed in ./config/openvpn/config.ovpn the container won't start and doesn't give a clear explanation whats wrong:
```log
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[cont-finish.d] executing container finish scripts...
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

## Current setup

| Docker image tag | latest |
| -------------------------------------------------------- | --- |
| Docker image hash | e71bb662bd74 |
| Host OS | Ubuntu 20.04 on WSL 2 |

## `docker-compose.yml`

```yaml
version: "3.3"
services:
  alpine-qbittorrent-openvpn:
    container_name: qbittorrent-openvpn
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    volumes:
      - ./downloads:/downloads
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1000
      - LAN=192.168.0.0/16
    ports:
      - "8080:8080"
    image: guillaumedsde/alpine-qbittorrent-openvpn:latest
```

## Attempted Fix(es)

- I've tested and changed, removed and left empty the OPENVPN_USERNAME, OPENVPN_PASSWORD and OPENVPN_PROVIDER parameters, but that didn't change anything.
- I've checked the .ovpn profile, and it's working fine.
