### ISSUE TITLE
Executing script after tunnel up

### ISSUE THREAD

**Issue by Ricardo-0101** [guillaumedsde/alpine-qbittorrent-openvpn#88]
Sorry if this is the wrong place to post this, I've been struggling to work out how with this container to execute a script once the tunnel comes up.  The purpose if this is to update via an API the IP assigned to the VPN.

As a fallback I know I can add `up /pathtoscript/script.sh` to my .ovpn file but I suspect there is a more elegant way to do this, the haugene container for example exectutes `/scripts/openvpn-post-config.sh`.

## Current setup
```yaml
version: "3.3"
services:
  alpine-qbittorrent-openvpn:
    container_name: alpine-qbittorrent-openvpn
    restart: unless-stopped
    image: guillaumedsde/alpine-qbittorrent-openvpn:latest #guillaumedsde/alpine-qbittorrent-openvpn:dd4cd24 
    volumes:
      - /mnt/downloads/:/downloads
      - /mnt/temp_downloads:/temp_downloads
      - ${USERDIR}/docker/qbittorrent:/config
      - ${USERDIR}/docker/shared/privado/##########:/config/openvpn/config.ovpn
      - ${USERDIR}/docker/shared/mam:/mam 
      - ${USERDIR}/docker/qbittorrent/scripts:/scripts
      - /etc/localtime:/etc/localtime:ro
    environment:
      - OPENVPN_PROVIDER= #Leave empty if provider not in the supported list
      - OPENVPN_USERNAME=###########
      - OPENVPN_PASSWORD=#########
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - QBT_WEBUI_PORT=8090
      - LAN=#############
    ports:
      - "8090:8090" #Unifi controller uses 8080
    cap_add:
      - NET_ADMIN
    labels:
      - com.centurylinklabs.watchtower.enable=true
```
